# Generated by Django 5.0.2 on 2024-07-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('IT', 'IT'), ('PCO', 'PCO'), ('Retail', 'Retail')], max_length=20)),
                ('established', models.DateField(auto_now=True)),
                ('working', models.BooleanField(default=True)),
                ('about', models.TextField()),
            ],
        ),
    ]
