# Generated by Django 5.0.2 on 2024-07-03 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapi', '0003_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('employee', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='newapi.employee')),
            ],
        ),
    ]
